language: java
dist: trusty
jdk:
  - openjdk8
sudo: false
global:
    - GPG_DIR="`pwd`"
#SONATYPE_USER
    - secure: "A0XXwwQlxC3vNsSbyiMZsOZ/Jz/Cg9a/BILeidI1FkcMOaHlHLxSZ6/SdJ81T8TiGR5eHzs1vsADvChnVcLzU5vRPgEXwMvN8DE+PZ0i5N/XniEiofnthjNu6RbwIBNmxd3wjKlTOUj2DuuRmjDev1a9DGO1WjUT89YczL4swLTI161cDkxv4UJXRgjfQ4ooWqK6b0/kLxOqFxPdiZ6lmAMqJxWd629ss73jb6FjMdmH/hjyhqgYC8T4I6FSYbedyvfpG0cAwMnqUobKlVxXPP0NO3rCOVSGeKW9gBq/D3JkZ7M3gKn6KGoUx7m2qFthyKz2NfdN5e3mTm+CXSwJVDK1qJW+g+ITafva+M7b/d5Knf1BsW963xIuMUfcFE043ZCdDgjX/ZtykxZ+XX1GA2qIK1BQgOH5RFiYRV6wRLOvITFT0Mx0tk4/NnMG36m71yccvYhznheZfXytnJE+F5jQqB0sd4SAmqd+rAg/W+6KhJRPt80+mcs800NCzG1Bz8YrYG6oxEEUkDyL6SKszlHVdjsXXPLM5VID1dsbn5UxVdnNq/B/QNzDxa+/BmjCbbh3APgIG4+4+BQbD7yVQl8EhBK84tyrz1AO+zXvHUZiTNX6WBe+SL6SbGnyst1vrOxmwZP1n9j373xLJjThbgaKZrC+yiRWTb5aW20x5wU="
#SONATYPE_PASSWORD
    - secure: "MS6LIBHDRC9LSLcqjrWCeuyx+kJP/ckJ32FMVerwxcSbA3/CBgnYlBPAFXk7zlDTAYQ4UaTT7FMTncSCaWvghxi+pTqLi2+r1gbmloM+KxVWWpRKXKlN2K7XBoRG86aWeIYVRf0B/jch/QFpnLUEMjLaaNemIpKHTtYmVSUuEzWBks8y3wLBwJ+ugUpXkX2FcOwpvRA2uZvUHKjMavdpt1fXK+VbtsCYIQY7+dsQ/iXIC7pQ+06TaiLP5DvwKLaIfrXfF0FOf8khhons5VRuyQGIuuzRT8NPPKrgFm2YTCTFVkb5MSsEyTglZdgTo8/29SDO35D9pkGCBAYo8q7l+SyhibzXBLdjX5AyrXkH2/Nj83o1qosWxGUPMQMusjW7McQo2GT4v/uY5hq0neY8LAT4MX2g324JLf2KLltuhfUJbfVRvumWQQQBFQAlyGbQ3xCaz19FuxC3lBKcOrkofCRfde4ubp3ACbTlWvzNJBBqEjpn651EktoCid4oX8YVtDxRvWGI5Q8drv5qwua9xU6nH/a9FxWqqdTujmKjOFVS7PRzyuxOVJ7ghQv4oTiT+u1w2xwZlNj0Zj2HoKqFQGr7M+7RBijT3djWmsozYVghWbIqQ0GIkWVVyFj/6v/RsLRDcAHtUnsEupoGKJ0b/UDa5ELR71K51vesE9noKZc="
#GPG_PASSPHRASE
    - secure: "Kpsfjdf2BFjzjh0VYVW8DtrnWVTozlKyPpZHIEmKQfF2v8JODdZoC5FZb8w3yoH6hKvSF+qAtkqpuzl8u1hTRd7g4VjnHUnvXJ1boHLduk50eRAR2BTbZAeUnD4lMWeA6Fo4dbfaiGST9KCJXJU9jFqnzXUzyrg0NIWBtAf9tyiwoo7JV1upV8JzWKbSMhdM7opHOHhd5eZ95ZNuXFL9f9uWxeyi+tLRSnIrKe8X1XBZQboQT/kHIC+QTZTqCANDIttwjiNdyE/zargek1r8dkktdsT0mxYh3GNE6KqEM4IVDfjWpbdHDwNazpEh/sxWarGQeaw+ZfXvj6vEwFcBnombd4SFNJE/gy62FSA1yPRxI06CIEvFM+XwqnAWsMZMFYTY4eBzCR/OlzRRBsjJg+qiRleSsMuvdyc+CLFIq4kVwJGTGto8Cs20Ov27nX22iWn83hFuJV2QqPCiT9CrbNedbPC6JCRI7FM2BrDabIeOsjUsdv1VY32L4QZSHm/dkXjmHJa++uEgvB2rHprbDuRDMkGyg/Ueh35LRdPtLbkBSKHt3F2OKpjlkUNG0dyVNARaipSTvM2US0p33OztMCu0A0F3EALWuXMZMAvZx4och0CjP/K0cnQUbPl2J8vVQ1Bfl8B5nZbjf1+dE/Vp4GOGUtBERhoSMYH0rJQFFyo="

install:
    - mvn versions:set -DnewVersion=$TRAVIS_BRANCH
    - mvn -B -Ptravis install
    
#addons:
#  sonarcloud:
#    organization: "ericsson-mts" # the key of the org you chose at step #3
#    token:
#      secure: "I6T9NCqXnQa3R9a/HJRv/iA8+TvWNSUGojzOyl+gPm4IqJ0wRAhmh8UmS68CIZgHbh1WokvEQfO5eTtDR2nYcQXR6xumV53D8V00vwiThdarKxQaB8TlP9fSB9ip7xFM29Wdt7/75q6SafPJS/QzXbFoRHhIPufWQDFSu7hACYmfvwWABAgVNNMoqwPy/LY5gzBPgfDUUGQxuaf4tAGNqQE2h77kpm6g9v+mJatSivB9lWAMt6dYxsNIJfYlGURH0hgPgiv7o82vi+P2+2ZucFYrNmD84wpGqbRg6tryFBEtVgEI8caVQa7YCfP2Q2rkl+V9tff7azUGODc5+6wbE2fQxIjnsrR4DrpUA7nyT5k/vugPeQWR9O7JUWnHNy+TKuf5loGt/OudC+f+EFMD608My9zeyMh7Jvc/ORnIyRaZh/UEmZX4pDuaDL9p9GnSXmeJJPGWlVBex70Ed7JgX9bJ2dSAUOEeCBsh2LshCzkmWDgOifgjGvT7r+/FBGMNbfgMvqVrH9cWjb0VQTYb053qDZBl9JsnXEHa3A1WiZoHbXzu2SpuhV1c3uyAqkAiyVE4PfZryEdIYMTifUPFy+LlObg/nXxIMp5Y1xjMUP/xm3iYX1vat9GHNFrjeUOVUEAGu+9ducPQ2SUrHiuUpT+MzqKpSLYRbZjt7ncTrvc="

#script:
#  # other script steps might be done before running the actual analysis
#  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.host.url=https://sonarcloud.io

cache:
  directories:
    - '$HOME/.m2/repository'
